### ISSUE TITLE
Can't handle "&" in value part

### ISSUE THREAD

**Issue by chris-kwng** [gmantaos/Commander.NET#1]
Hi G. Mantaos,

your Commander.NET can't handle "&" (maybe spaces as well) in the parameter value part.

For example:
> MyApp -p abc&def

Turns into:
> MyApp -p abc & def

This way **def** is recognized as a command. **0o**

Okay, so i tried to put the value in quotes (as usual in console applications):
> MyApp -p "abc&def"

But then the quotes will **not** be removed.

So I have to deal with them. :-/

...do I really have to??? ...or is there a secret parser option?

The quotes only should make sure that the complete value will be read (e.g. a path with spaces), but they should not be included i think, don't you?

Thanks & best regards,
Chris

**Comment by haath** [comment]
Hello there and thanks for the feedback.

No this does not sound intended at all, can you post an example of how you're calling the parser?

Cheers,
Greg

**Comment by haath** [comment]
I made the assumption that you were trying to parse a custom string instead of actual command-line args passed by your shell, so I took another look at how I had handled the string parsing and sure enough there was room for improvement.

It may not be related to your issue, but have a go with `1.1.9` which you should be listed on NuGet in a moment. If that doesn't fix it then show me your code so I can add it to the [test cases](https://github.com/gmantaos/Commander.NET/blob/master/Commander.NET.Tests/UtilsTests.cs).

Greg

**Comment by chris-kwng** [comment]
Hi Greg,

sorry about the late reply.

Here is my example app:
```
namespace MyApp
{
    class Program
    {
        class Options
        {
            [Parameter("-p", Description = "Parameter")]
            public string Parameter = string.Empty;
        }

        static void Main(string[] args)
        {
#if DEBUG
            args = new string[2];
            args[0] = "-p";
            args[1] = "\"abc&def\"";
#endif

            var parser = new CommanderParser<Options>();
        
            if (args == null || args.Length < 1)
            {
                Console.WriteLine(parser.Usage());
            }
            else
            {
                var options = parser.Add(args).Parse();

                Console.WriteLine(options.Parameter);
            }
        }
    }
}
```

If you call the release with a batch like this...
```
MyApp -p abc&def
PAUSE
```
...you will get the following result:
```
C:\...\Projects\MyApp\bin\Release>MyApp -p abc  & def
abc
The command "def" is either misspelled or could not be found.
```

The problem with the quotes only occures if I create my own args array (see #if DEBUG).
It is working, if I use the command line arguments in the boot options of the project.

So this is my fault, sorry! :-)

Best regards,
Chris

**Comment by haath** [comment]
Yes the first one is expected, it's normally the shell's responsibility to parse the string and split it into arguments, so the `string[] args` that gets passed to `Main` should have already put the contents of quotes properly into the array. To debug your application you can do one of two things.

Construct the `args` array as the shell would, without quotes.

```csharp
arg = new string[]{ "-p", "abc&def" };
```

Or use a string.

```chsarp
var options = parser.AddLine("-p \"abc&def\"").Parse();
```

As for `&` splitting up your arguments, it appears that this is the default behavior for the Windows batch shell and will even throw an error if it is attempted in Powershell. So you'll have to wrap your argument in quotes.

**Comment by chris-kwng** [comment]
Thank you very much and sorry for the ticket and your time!

**Comment by haath** [comment]
No worries, glad to help
